baseURL = "https://marbletrack3.com/"
languageCode = "en-us"
DefaultContentLanguage = "en"

#googleAnalytics = "UA-100789009-1"
#disqusShortname = "arresteddevops"
paginate = "9"


[languages]
  [languages.en]
    title = "Marble Track 3"
    weight = 1
    LanguageName = "EN"
    description = "Livestreams of the Stop Motion Animation of the [Construction of Marble Track 3](https://mt3s.marbletrack3.com)"

[[languages.en.Menu.Main]]
    name = "Workers"
    identifier = "030_workers"
    url = "workers"

[[languages.en.Menu.Main]]
    name = "Track"
    identifier = "050_parts"
    url = "parts"

#[[languages.en.Menu.Main]]
#    name = "Step by step"
#    identifier = "060_snippets"
#    url = "snippets"
#
#[[languages.ja.Menu.Main]]
#    name = "Step by step"
#    identifier = "060_snippets"
#    url = "snippets"

[[languages.en.Menu.Main]]
    name = "Thanks"
    identifier = "070_thanks"
    url = "thanks"

[[languages.en.Menu.Main]]
    name = "Support"
    identifier = "080_support"
    url = "support"

  [languages.ja]
    title = "ビー玉からくり第三弾"
    weight = 2
    LanguageName = "JA"
    description = "Livestreams of the Stop Motion Animation of the [Construction of ビー玉からくり第三弾](https://mt3s.marbletrack3.com)"

    [languages.ja.params]
      [languages.ja.params.navigation]
        help = "Aide"

[[languages.ja.Menu.Main]]
    name = "社員"
    identifier = "030_workers"
    url = "workers"

[[languages.ja.Menu.Main]]
    name = "Track"
    identifier = "050_parts"
    url = "parts"

[[languages.ja.Menu.Main]]
    name = "Thanks"
    identifier = "070_thanks"
    url = "thanks"

[[languages.ja.Menu.Main]]
    name = "Support"
    identifier = "080_support"
    url = "support"

[permalinks]
        blog = "/blog/:year/:month/:day/:title/"
	# page = "/:filename/"
	episode = "/episode/:year/:monthname/:title/"

# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier

#[[languages.en.Menu.Main]]
#    name = "About"
#    identifier = "010_about"
#    url = "about"
#
#[[languages.en.Menu.Main]]
#    name = "FAQ"
#    identifier = "020_faq"
#    url = "faq"
#
#[[languages.en.Menu.Main]]
#    name = "Episodes"
#    identifier = "040_episode"
#    url = "episode"
#
#[[languages.en.Menu.Main]]
#    name = "Future"
#    identifier = "060_future"
#    url = "future"
#[[languages.ja.Menu.Main]]
#   name = "概要"
#   identifier = "010_about"
#   url = "about"
#
#[[languages.ja.Menu.Main]]
#    name = "FAQ"
#    identifier = "020_faq"
#    url = "faq"
#
#[[languages.ja.Menu.Main]]
#    name = "Episode"
#    identifier = "040_episode"
#    url = "episode"
#
#[[languages.ja.Menu.Main]]
#    name = "後の予定"
#    identifier = "060_future"
#    url = "future"


[params]
site_theme = "blue"
site_layout = "grid"
# site_layout = "row"
enable_jumbo = "true"
# enable_jumbo = "false"
# truncate = "100"
# about_logo = "/img/hugocast.png"
copyright_notice = "Copyright 2019 [Rob Nugen](https://www.robnugen.com)"
reserved_text = "All rights reserved."
#itunes_subscribe = "http://itunes.apple.com/us/podcast/arrested-devops/id773888088?mt=2&uo=4&at=11lsCi"
#android_subscribe = "http://subscribeonandroid.com/feeds.podtrac.com/VGAulpN7MY1U"
#google_play_subscribe = "https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ihj4yege3lfmp3vs5yoopgxijpi?t%3DArrested_DevOps"
#stitcher_subscribe = "http://www.stitcher.com/podcast/arrested-devops-2/arrested-devops"
#soundcloud_subscribe = "http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
#pocketcasts_subscribe = "http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
#mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
media_prefix = "https://media.blubrry.com/"
# Replace Logo image at 'static/img'.
    # Add Header logo 
        logo = "/img/logo.png"
    # Add Footer logo 
        ft_logo = "/img/logo-footer.png"

# Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "your@email.com"

  [params.feed]
     feed_copyright = "Copyright 2016 Rob Nugen" #do not use markdown in this field; it is used in the feed
#    itunes_subtitle = "The best podcast ever" #no markdown or HTML
#    itunes_author = "Matt Stratton" #no markdown or HTML
#    itunes_summary = "" # Limited to 4000 characters or less, plain text, no HTML
#    itunes_owner_name = "Matt Stratton"
#    itunes_owner_email = "matt.stratton@gmail.com" # not be publicly displayed on iTunes.
#    itunes_image = "https://www.arresteddevops.com/img/ado-podcast-logo.png" #fqdn to the image art for your podcast
#    itunes_top_category = "Technology"
#    itunes_first_sub_category = "Software How-To"
#    itunes_second_sub_category = "Tech News"


  [params.social]
     github = "marbletracks"
#    gitlab = "mattstratton"
#    facebook = "Arresteddevops"
#    facebook_admin = "500557137"  # This needs to be a page admin to get domain insights
     twitter = "marbletracks"
#    twitter_domain = "arresteddevops.com" # This domain shows in twitter cards as "View on `twitter_domain`"
#    googleplus = "ArrestedDevOps"
#    pinterest = "nozzleio"
#    instagram = "nozzleio"
    youtube = "channel/UCHiQhB8J_KI2LYQ7dsexfLw"
#    linkedin = "mattstratton"

  [params.authors]
    [params.authors.Matt]
      name	= "Rob Nugen"
      thumbnail = "https://b.robnugen.com/art/marble_track_3/creators/rob_nugen.jpg"
      bio = "In the real world, Rob leads peer counseling circles in Tokyo with the long term goal of lowering the suicide rate in Asia"
      [params.authors.Matt.social]
        github = "thunderrabbit"
        facebook = "thunderrabbit"
        twitter = "thunderrabbit"
        homepage = "https://www.robnugen.com"
        instagram = "hadashiusagi"
        youtube = "thunderrabbit"

    [params.links]
      [params.links.ado]
        name = "Arrested DevOps"
        url = "https://www.arresteddevops.com"

 [params.top_banner]
  title = "Marble Track 3 Construction"
  video = "https://b.robnugen.com/art/marble_track_3/workers/snippets/quick_look_help_you_up.mp4"
  description = "This website follows their progress, tracking who made what, and how all the parts fit together."

[params.latest_track]
    enable = true
    title = "TRACK" 
    subtitle = "(PARTS)"

[params.our_workers]
    enable = true
    title = "Our Workers"

[params.snippets]
    enable = true
    title = "SNIPPETS"
    subtitle = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer."

[params.support_banner]
    enable = true
    title = "Support"
    description = "You can support Marble Track 3 Construction in a variety of ways. Once Marble Track 3 Construction is finished, the person or entity who has given the most support will receive the actual Marble Track 3 track itself."
    button_text = "[Become A Supporter] (https://www.paypal.me/marbletrack3)"
   
[params.home_video]
    enable = true

[params.contact_form]
    enable = true
    title = "Questions or comments?"
    subtitle = "Ideas, questions, comments are all welcome."
